name: vitemoncarburant
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-109.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  flutter_easyloading: ^3.0.3
  flutter_launcher_icons: ^0.9.2
  google_fonts: ^2.2.0
  geolocator: ^8.0.3
  custom_refresh_indicator: ^1.0.0
  map_launcher: ^2.1.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env.development
    - .env.production

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon_white.png"
